---
- name: Create Redis config file
  template:
    src: redis.conf.j2
    dest: /etc/redis_{{ item.port }}.conf
    mode: 0644
    force: yes
    owner: root
    group: root
    backup: no
  when: ansible_default_ipv4.address == "{{ item.ip }}"
  with_items: "{{ redis_cluster }}"

- name: Create Redis init script
  template:
    src: redis.j2
    dest: /etc/init.d/redis_{{ item.port }}
    mode: 0755
    force: yes
    owner: root
    group: root
    backup: no
  when: ansible_default_ipv4.address == "{{ item.ip }}"
  with_items: "{{ redis_cluster }}"