---
- name: Try to shutdown running Redis gracefully
  shell:
    netstat -nlpt | grep redis | awk '{print $7}' | cut -d / -f 1 | xargs -r kill -15
  args:
    executable: /bin/bash
    
- name: Kill Redis forcefully to make sure no Redis instance is running
  shell:
    netstat -nlpt | grep redis | awk '{print $7}' | cut -d / -f 1 | xargs -r kill -9
  args:
    executable: /bin/bash

- name: Delete Redis pid file to guarantee a sucessful restart
  shell:
    rm -rf {{ redis_run_path }}/*redis*
  args:
    executable: /bin/bash
    
- name: Start all Redis instance    
  service:
    name: redis_{{ item.port }}
    state: started
  when: ansible_default_ipv4.address == "{{ item.ip }}"
  with_items: "{{ redis_cluster }}"